repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
#      - id: double-quote-string-fixer
#      - id: mixed-line-ending
#        args: [ --fix=crlf ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
      # - id: pretty-format-json
      - id: requirements-txt-fixer
#      - id: trailing-whitespace
#        args: [ --markdown-linebreak-ext=md ]


  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--write, --toml, pyproject.toml]
        additional_dependencies:
          - tomli

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
      language_version: python3
