name: Deployment Pipeline

on:
  push:

jobs:
  Pre-Commit-and-Document-Check:
    uses: ./.github/workflows/01-pre-commit-and-document-check.yml

  # CI:
  #   needs: Check-Documentation
  #   uses: ./.github/workflows/03-ci.yml
  #   secrets: inherit

  Build-and-Deploy-to-Production:
    needs: Pre-Commit-and-Document-Check
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/04-build-and-deploy-to-production.yml
