name: CI

on:
  workflow_call:

jobs:
  CI:
    runs-on: ${{matrix.os}}
    env:
      GH_REPO_ACCESS_BY_OWN_APPS: ${{ secrets.GH_REPO_ACCESS_BY_OWN_APPS }}
      VENV_ENVIRONMENT: ${{vars.VENV_ENVIRONMENT}}

    strategy:
      fail-fast: true
      matrix:
        #        python-version: ['3.8', '3.9', '3.10', '3.11']
        # python-version: [ '3.12' ]
        #        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: [ 'windows-latest' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up PowerShell
      # uses: actions/setup-powershell@v3

    - name: Install Pester
      shell: pwsh
      run: Install-Module -Name Pester -Force -Scope CurrentUser

    # - name: Run Pester Tests
    #   working-directory: ./solution
    #   run: |
    #     $config = New-PesterConfiguration
    #     $config.Run.Path = "."
    #     $config.CodeCoverage.Enabled = $true
    #     $config.TestResult.Enabled = $true
    #     Invoke-Pester -Configuration $config

    - name: Run Pester Tests
      run: |
        $testResults = Invoke-Pester -Path "./tests" -PassThru
        if ($testResults.FailedCount -gt 0) {
          throw "There are failing tests!"
        }

    - name: Upload code coverage report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: solution\coverage.xml


